# Generated by Django 5.0.4 on 2024-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Doctor care', 'Doctor care'), ('Nursing care', 'Nursing care'), ('Medical social services', 'Medical social services'), ('Homemaker or basic assistance care', 'Homemaker or basic assistance care')], default='Doctor care', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.CharField(choices=[('Neurologist', 'Neurologist'), ('Cardilogist', 'Cardilogist'), ('Pediatrician', 'Pediatrician'), ('Physiotherapy', 'Physiotherapy')], default='Neurologist', max_length=50),
        ),
    ]
